# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=255, unique=True)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('ip', models.CharField(default=None, max_length=15)),
                ('latitude', models.DecimalField(decimal_places=6, default=None, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, default=None, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
    ]
