# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_browser', '0002_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateField(default=None, null=True),
        ),
    ]
