# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_browser', '0003_auto_20160609_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
